-- AlterTable
ALTER TABLE `Plan` ADD COLUMN `giftDeliveryAddress` VARCHAR(191) NULL,
    ADD COLUMN `giftDeliveryChoice` ENUM('UNDECIDED', 'HAND_IN_PERSON', 'SHIP') NOT NULL DEFAULT 'UNDECIDED',
    ADD COLUMN `giftPurchaseStatus` ENUM('PURCHASED', 'NOT_PURCHASED') NOT NULL DEFAULT 'NOT_PURCHASED';
